#!/bin/sh

## Set startup volume
pactl set-sink-volume 1 -- '20%' &

## Set LCD brightness
xbacklight -set 50 &

## Activate CAPS LOCK as compose key
xmodmap ~/.Xmodmap &

## Notification daemon
dunst &

## Setup montiors for work
xrandr --output VGA1 --auto --left-of eDP1
