#!/bin/bash

PWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
HOST=$(cat "$PWD/../host")

## Set startup volume
amixer -q -D pulse set Master 20% unmute &
#pactl set-sink-volume 1 -- '20%' &

## Set LCD brightness
if [ "$HOST" != "home" ] ; then
  xbacklight -set 50 &
fi

## Set gb as keyboard layout
setxkbmap gb

## Activate CAPS LOCK as compose key
xmodmap ~/.Xmodmap &

## Notification daemon
dunst &

## Setup montiors for work
if [ "$HOST" == "home" ] ; then
  xrandr --output HDMI-0 --auto --primary
  xrandr --output DVI-1 --auto --left-of HDMI-0 --auto
elif [ "$HOST" == "work" ] ; then
  xrandr --output eDP1 --auto --primary
  xrandr --output VGA1 --auto --left-of eDP1
fi
